language: node_js

os:
- osx
- linux

node_js:
- 8
- 10
- 12
- 13

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - npm install -g vsce

script:
  - yarn
  - yarn compile
  - yarn test
  - yarn run package

cache: yarn

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: *.vsix
  skip_cleanup: true
  on:
    tags: true
