language: node_js
os:
- osx
- linux
node_js:
- 8
- 10
- 12
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
    npm install -g vsce

script:
  - |
    echo ">>> Compile vscode-test"
    yarn && yarn compile
    echo ">>> Compiled vscode-test"
    cd sample
    echo ">>> Run sample integration test"
    yarn && yarn compile && yarn test
    npm run webpack:compile
    npm run vscode:prepublish
    vsce package

cache: yarn


deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: bangumiopen-1.1.1.vsix
  skip_cleanup: true
  on:
    tags: true
