language: node_js

os:
- osx
- linux

node_js:
- 8
- 10
- 12
- 13

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - npm install -g vsce
  - npm install -g nyc

script:
  - yarn
  - yarn compile
  - nyc --reporter=html --reporter=text yarn test
  - nyc report --reporter=text-lcov > coverage.lcov
  - npm run webpack:compile
  - npm run vscode:prepublish
  - vsce package

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: yarn

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: bangumiopen-1.2.0.vsix
  skip_cleanup: true
  on:
    tags: true
