trigger:
  - master
  - SDTTTTT
  - CICD

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageName: "vs2017-win2016"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: |
      npm install -g vsce
    displayName: Install VSCE

  - bash: |
      yarn
      yarn compile
      yarn test
    displayName: Run Tests
    env:
      DISPLAY: ":99.0"

  - bash: |
      npm run webpack:compile
      npm run vscode:prepublish
      vsce package
    displayName: Packing

    